### ISSUE TITLE
paste to clipboard prints char by char, needs to be optimized

### ISSUE THREAD

**Issue by austinthiel** [austinthiel/CopyMore#24]
Maybe writeBuffer? 

https://github.com/electron/electron/blob/master/docs/api/clipboard.md#clipboardwritebufferformat-buffer-type-experimental

**Comment by LandonHammond** [comment]
writeBuffer is for writing a buffer into the clipboard. None of these clipboard functions support actually writing/printing out the data to the system. The reads read what is currently in the clipboard, and the writes write it into the clipboard.

writeBuffer is going to be useful for copying file data into the clipboard

**Comment by austinthiel** [comment]
#25
